const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));history.replaceState(null,'','#'+id);window.scrollTo({top:0,behavior:'instant'});if(id==='carte')setTimeout(()=>map&&map.invalidateSize(),80);localStorage.setItem('cn26_v11_view',id)}
$$('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();showView(el.dataset.view)}));
const imageAlts={'chengdu.jpg':'Vue de Chengdu','mont-emei.jpg':'Mont Emei','leshan.jpg':'Grand Bouddha de Leshan','jiuzhaigou.jpg':'Lacs de Jiuzhaigou','huanglong.jpg':'Bassins de Huanglong','dujiangyan.jpg':'Dujiangyan','qingcheng.jpg':'Mont Qingcheng','chongqing.jpg':'Chongqing','huangguoshu.jpg':'Chutes de Huangguoshu','kaili.jpg':'Kaili','fanjing.jpg':'Mont Fanjing','qingyan.jpg':'Qingyan','opera-sichuan.jpg':'Opéra du Sichuan'};
const days=$('#days');ITINERARY.forEach((d,i)=>{const article=document.createElement('article');article.className='day';article.id='jour-'+(i+1);const img=d.image?`<img class="day-image" src="images/${d.image}" alt="${imageAlts[d.image]||''}" loading="lazy">`:'';const transport=d.transport?`<p class="transport">${d.transport}</p>`:'';const booking=d.booking_url?` <a class="booking-link" href="${d.booking_url}" target="_blank" rel="noopener noreferrer">Réservation</a>`:'';article.innerHTML=`<p class="day-date">${d.date}</p><h2 class="day-route">${d.route}</h2>${transport}${img}<div class="day-details"><ul class="sites">${d.sites.map(s=>`<li>${s}</li>`).join('')}</ul><p class="night"><strong>${d.night_city}</strong> · ${d.night}${booking}</p></div><button class="note-toggle" aria-expanded="false">Note personnelle</button><textarea class="day-note" placeholder="Impressions, adresse, souvenir…"></textarea>`;const toggle=$('.note-toggle',article),note=$('.day-note',article),key='cn26_v11_note_'+i;note.value=localStorage.getItem(key)||'';if(note.value){toggle.textContent='Note personnelle enregistrée'}toggle.onclick=()=>{const open=note.classList.toggle('open');toggle.setAttribute('aria-expanded',open);if(open)note.focus()};note.oninput=()=>{localStorage.setItem(key,note.value);toggle.textContent=note.value?'Note personnelle enregistrée':'Note personnelle'};days.appendChild(article)});
let map=null;if(window.L){map=L.map('map',{scrollWheelZoom:false});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(map);const pts=[];ITINERARY.forEach((d,i)=>{if(!d.lat||!d.lon)return;pts.push([d.lat,d.lon]);const icon=L.divIcon({className:'',html:`<div class="map-marker">${i+1}</div>`,iconSize:[27,27],iconAnchor:[13,13]});L.marker([d.lat,d.lon],{icon}).addTo(map).bindPopup(`<strong>${d.date}</strong><br>${d.route}<br><a href="#jour-${i+1}" data-day="${i+1}">Voir la journée</a>`)});L.polyline(pts,{color:'#8b332c',weight:3,opacity:.75}).addTo(map);map.fitBounds(pts,{padding:[25,25]});map.on('popupopen',()=>{$$('[data-day]').forEach(a=>a.onclick=e=>{e.preventDefault();showView('voyage');setTimeout(()=>$('#jour-'+a.dataset.day).scrollIntoView({behavior:'smooth'}),50)})})}
const mapList=$('#map-list');ITINERARY.forEach((d,i)=>{const el=document.createElement('div');el.className='map-stop';el.innerHTML=`<span>${d.date.replace(' 2026','')}</span>${d.route}`;mapList.appendChild(el)});
let userBudget=JSON.parse(localStorage.getItem('cn26_v11_budget')||'[]');const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n);const items=()=>[...SEED_BUDGET,...userBudget];
function renderBudget(){const all=items(),total=all.reduce((s,x)=>s+Number(x.amount),0),paid=all.filter(x=>x.status==='Payé').reduce((s,x)=>s+Number(x.amount),0),due=total-paid;$('#budget-summary').innerHTML=`<div class="budget-stat"><span>Total suivi</span><strong>${money(total)}</strong></div><div class="budget-stat"><span>Déjà payé</span><strong>${money(paid)}</strong></div><div class="budget-stat"><span>Reste ou prévu</span><strong>${money(due)}</strong></div>`;const groups=$('#budget-groups');groups.innerHTML='';[...new Set(all.map(x=>x.category))].forEach(cat=>{const list=all.filter(x=>x.category===cat),section=document.createElement('section');section.className='budget-group';section.innerHTML=`<h2>${cat}</h2>${list.map(x=>`<div class="expense-row"><span>${x.label}</span><span class="amount">${money(x.amount)}</span><span class="status">${x.status}</span>${x.id?`<button class="remove" data-remove="${x.id}" title="Supprimer">×</button>`:''}</div>`).join('')}<div class="group-total">Total ${cat.toLowerCase()} : ${money(list.reduce((s,x)=>s+Number(x.amount),0))}</div>`;groups.appendChild(section)});$$('[data-remove]').forEach(b=>b.onclick=()=>{userBudget=userBudget.filter(x=>x.id!==b.dataset.remove);localStorage.setItem('cn26_v11_budget',JSON.stringify(userBudget));renderBudget()})}renderBudget();
const dialog=$('#expense-dialog');$('#add-expense').onclick=()=>dialog.showModal();$('#save-expense').onclick=e=>{const label=$('#expense-label').value.trim(),amount=Number($('#expense-amount').value);if(!label||!amount){e.preventDefault();return}userBudget.push({id:String(Date.now()),category:$('#expense-category').value,label,amount,status:$('#expense-status').value});localStorage.setItem('cn26_v11_budget',JSON.stringify(userBudget));renderBudget();$('#expense-form').reset()};
$('#export-budget').onclick=()=>{const all=items(),lines=['BILAN DU VOYAGE EN CHINE 2026','','Catégorie;Description;Montant (€);Statut',...all.map(x=>`${x.category};${x.label};${Number(x.amount).toFixed(2)};${x.status}`),'',`TOTAL;;;${all.reduce((s,x)=>s+Number(x.amount),0).toFixed(2)}`],blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='bilan-voyage-chine-2026.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const requested=location.hash.slice(1);showView(['voyage','carte','budget'].includes(requested)?requested:(localStorage.getItem('cn26_v11_view')||'voyage'));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js').catch(()=>{}));
